### PR TITLE
⚡ Next13.3 | app dir

### PR DESCRIPTION
**Pull request by salvaoo**
[Configuration changes](https://github.com/shadcn/next-template/pull/4/commits/4242918d8eab5d792e125944fd67255ff853f3bb)
- `Package.json` updated.
- App dir config added to setting files.

[Nextjs app dir changes](https://github.com/shadcn/next-template/pull/4/commits/f5295017a9f7dd6c5e77d09a8583c2879a336b8a)
- `_app.tsx, _document.tsx, index.tsx` from pages folder deleted and new `app` folder added.
- Templates and Layouts adapted to Next.js 13.3 and app dir.
- `@next/font` updated to `next/font`.

### CODE REVIEW

**Comment by shadcn** [comment]
@salvaoo so the idea here is to keep this template using `pages` and add a new one that uses `app` dir when it goes stable.

I'm going to think how we can handle both and get back to this PR.

Appreciate the help. Thank you

**Comment by Roopaish** [comment]
@salvaoo  I am getting this error with your pull request.

Failed to compile
```bash
./components/ui/dropdown-menu.tsx
Module parse failed: Bad character escape sequence (2:98)
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"
> const proxy = createProxy("W:\rupes\Documents\Workspace\hyperce\e-kagajpatra frontend\components\ui\dropdown-menu.tsx")
| 
| // Accessing the __esModule property and exporting $$typeof are required here.
```

**Comment by Roopaish** [comment]
@salvaoo  I am getting this error with your pull request.

Failed to compile
```bash
./components/ui/dropdown-menu.tsx
Module parse failed: Bad character escape sequence (2:98)
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"
> const proxy = createProxy("W:\next-template\components\ui\dropdown-menu.tsx")
| 
| // Accessing the __esModule property and exporting $$typeof are required here.
```

**Comment by Roopaish** [comment]
This issue was on Windows only mentioned here [#47736](https://github.com/vercel/next.js/discussions/47736)

**Comment by salvaoo** [comment]
@Roopaish From what I see it seems to be a problem that Next has been having for several versions.. 
Can you give me more information about it?

**Comment by Roopaish** [comment]
Yep, it was due to some issues with the Next.js versions, which only occur on Windows. I fixed the problem by clearing the .next folder and using `"next": "^13.3.1-canary.12"`. Your template is now working properly, although it takes 3-4 seconds to compile, which is understandable since I'm using unstable features.

**Pull request closed without merging**
